# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18iq2vlrWBp4os8CYJYRH2Xflaxc_WFVt
"""

from numpy import exp ,array , random , dot, mean, abs
import numpy

#inputları aldık
girdi = array([[0,0,1],[1,1,1],[1,0,1]])

gercek_sonuc =array([[0,1,1]]).T

#rastgele olarak girilen ağırlık değerleri
agirlik =array([[1.0,1.0,1.0]]).T

#10000 kere tahmin yapılmasını sağladık
for tahmin in range(100000):

  hücre_degeri= dot(girdi,agirlik) # genel formul olan y = a*w 

  tahmin = 1/(1 + exp(-hücre_degeri)) #sigmoid fonk. kullanılarak yapıldı 1/(1-exp(-hücre_değeri))
 
  agirlik = agirlik + dot(girdi.T,((gercek_sonuc - tahmin)*tahmin*(1-tahmin))) #optimum ağırlık değerini bulmaya yarıyor (formulden)

  print("hata oranı yüzde",str(numpy.mean(numpy.abs(gercek_sonuc-tahmin)*100)))#hata miktarını görmek için
print("tahmini değerler",      tahmin)#sonucu görmek için